rails/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :notes do
    member do
      get   'disclosures'       => "notes#show_disclosures"
      get   'disclosures/edit'  => "notes#edit_disclosures"
      patch 'disclosures'       => "notes#update_disclosures"
    end
  end
  resources :groups

  resources :users, :except => [:index, :show]
  resources :password_auths, :only => [:new, :create, :destroy]
  
  get 'login' => 'password_auths#new', :as => :login
  post 'logout' => 'password_auths#destroy', :as => :logout

  root :to => 'notes#index'
end

rails/app/models/note.rb
class Note < ApplicationRecord
  include FriendlyId
  friendly_id :code
  before_create ->{ self.code = SecureRandom.hex(10)  }

  belongs_to :owner, foreign_key: :owner_user_id, class_name: "User"
  has_many :disclosures, class_name: "NoteDisclosure", dependent: :destroy
  has_many :disclosed_groups, through: :disclosures, source: :group
  accepts_nested_attributes_for :disclosures, reject_if: ->(attrs){ attrs['group_id'].blank? }, allow_destroy: true

  scope :disclosed_to_or_owned_by, ->(user){
    eager_load(:disclosed_groups => {:group_users => :user}).where( 
      arel_table[:owner_user_id].eq( user.id ).or(
        GroupUser.arel_table[:user_id].eq( user.id)
      )
    ).distinct
  }

  def owned_by?(user)
    owner == user
  end

  def disclosure_of(group)
    disclosures.find_by(group: group)
  end

  def disclosed_to?(user_or_group)
    case user_or_group
    when User
      disclosed_to_user?(user_or_group)
    when Group
      disclosed_to_group?(user_or_group)
    else
      raise
    end
  end

  def disclosed_to_user?(user)
    disclosed_groups.including_user(user).any?
  end

  def disclosed_to_group?(group)
    disclosure_of(group).present?
  end

  def rest_disclosures_size
    3 - disclosures.size
  end

end

rails/app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :set_note, only: [:show, :edit, :update, :destroy, :edit_disclosures, :update_disclosures]
  before_action :check_permission_for_read, only: [:show]
  before_action :check_permission_for_write, only: [:edit, :update, :destroy, :edit_disclosures, :update_disclosures]

  # GET /notes
  # GET /notes.json
  def index
    @notes = Note.disclosed_to_or_owned_by(current_user)
                 .order(:updated_at)
  end

  # GET /notes/1
  # GET /notes/1.json
  def show

  end

  # GET /notes/new
  def new
    @note = Note.new
  end

  # GET /notes/1/edit
  def edit
  end

  # POST /notes
  # POST /notes.json
  def create
    @note = Note.new(note_params)
    @note.owner = current_user

    respond_to do |format|
      if @note.save
        format.html { redirect_to @note, notice: 'Note was successfully created.' }
        format.json { render :show, status: :created, location: @note }
      else
        format.html { render :new }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /notes/1
  # PATCH/PUT /notes/1.json
  def update
    respond_to do |format|
      if @note.update(note_params)
        format.html { redirect_to @note, notice: 'Note was successfully updated.' }
        format.json { render :show, status: :ok, location: @note }
      else
        format.html { render :edit }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notes/1
  # DELETE /notes/1.json
  def destroy
    @note.destroy
    respond_to do |format|
      format.html { redirect_to notes_url, notice: 'Note was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def edit_disclosures
    @note.rest_disclosures_size.times do
      @note.disclosures.build
    end
  end

  def update_disclosures
    respond_to do |format|
      if @note.update(note_disclosures_params)
        format.html { redirect_to @note, notice: 'Disclosures was successfully updated.' }
        format.json { render :show, status: :ok, location: @note }
      else
        format.html { render :edit }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end

  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_note
      @note = Note.friendly.find(params[:id])
    end

    def check_permission_for_read
      unless @note.disclosed_to?(current_user) || @note.owned_by?(current_user)
        redirect_to notes_path, alert: 'You cannot read this note.' 
        return
      end
    end

    def check_permission_for_write
      unless @note.owned_by?(current_user)
        redirect_to notes_path, alert: 'You cannot write this note.' 
        return
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def note_params
      params.require(:note).permit(:title, :text)
    end

    def note_disclosures_params
      _note_params = params.require(:note).permit(disclosures_attributes: [:id, :group_id])
      _note_params["disclosures_attributes"].each do | k, v |
        v["_destroy"] = true if v["group_id"].blank?
      end
      _note_params

    end

end

rails/app/helpers/notes_helper.rb
module NotesHelper
end

rails/app/views/notes/_form.html.erb
<%= simple_form_for _note do |f| %>
  <%= f.input :title %>
  <%= f.input :text, as: :text, input_html: {rows: 15, class: "markdown-edit"} %>

  <%= link_to "back", notes_path, class: "btn"%>
  <%= f.submit class: ["btn", "btn-primary"] %>
<% end %>

rails/app/views/notes/edit.html.erb
<h1>Editing Note</h1>

<%= render 'form', _note: @note %>

rails/app/views/notes/edit_disclosures.html.erb
<%= simple_form_for @note, url: disclosures_note_path(@note) do |f| %>
  
  <%= f.simple_fields_for :disclosures do |d| %>
    <%= d.input :group_id, collection: @note.owner.groups %>
  <% end %>

  <%= link_to "back", note_path(@note), class: "btn"%>
  <%= f.submit class: ["btn", "btn-primary"] %>
<% end %>

rails/app/views/notes/index.html.erb
<h1>Notes</h1>

<table class= "table">
  <thead>
    <tr>
      <th>owner</th>
      <th>title</th>
      <th>created_at</th>
      <th>updated_at</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @notes.each do |note| %>
      <tr>
        <td><%= note.owner.name %></td>
        <td><%= note.title %></td>
        <td><%= note.created_at %></td>
        <td><%= note.updated_at %></td>
        
        <td>
          <%= link_to 'Show', note, class: ["btn", "btn-sm", "btn-primary"] %>
          <%= link_to 'Edit', edit_note_path(note), class: ["btn", "btn-sm", "btn-info"] %>
          <%= link_to 'Destroy', note, method: :delete, data: { confirm: 'Are you sure?' }, class: ["btn", "btn-sm", "btn-danger"]  %>
        </td>
        
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Note', new_note_path, class: "btn btn-primary" %>

rails/app/views/notes/new.html.erb
<h1>New Note</h1>

<%= render 'form', _note: @note %>

rails/app/views/notes/show.html.erb
<div class="page-header">
  <h1><%= @note.title %></h1>
</div>

<div class="content-text">
  <%== Kramdown::Document.new(@note.text).to_html %>
</div>

<%= link_to 'Back', notes_path, class: "btn btn-default"%>
<%= link_to 'Edit', edit_note_path(@note), class: "btn btn-info" %>
<%= link_to 'EditDisclosures', disclosures_edit_note_path(@note), class: "btn btn-info" %>