rails/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :notes do
    member do
      get   'disclosures'       => "notes#show_disclosures"
      get   'disclosures/edit'  => "notes#edit_disclosures"
      patch 'disclosures'       => "notes#update_disclosures"
    end
  end
  resources :groups

  resources :users, :except => [:index, :show]
  resources :password_auths, :only => [:new, :create, :destroy]
  
  get 'login' => 'password_auths#new', :as => :login
  post 'logout' => 'password_auths#destroy', :as => :logout

  root :to => 'notes#index'
end

rails/app/models/group.rb
class Group < ApplicationRecord
  include FriendlyId
  friendly_id :code
  before_create ->{ self.code = SecureRandom.hex(10)  }

  belongs_to :owner, foreign_key: :owner_user_id, class_name: "User"
  has_many :group_users, dependent: :destroy
  has_many :including_users, through: :group_users, source: :user
  accepts_nested_attributes_for :group_users, reject_if: ->(attrs){ attrs['user_id'].blank? }, allow_destroy: true

  has_many :disclosures, class_name: "NoteDisclosure", dependent: :destroy
  has_many :disclosed_notes, through: :disclosures, source: :note

  scope :including_user, ->(user){
    joins(:group_users).where(:group_users => {user_id: user.id} )
  }

  scope :owned_by, ->(user){
    where(owner_user_id: user.id)
  }

  def owned_by?(user)
    owner == user
  end

  def include?(user)
    group_users.where(user: user).any?
  end

  def rest_users_size
    3 - group_users.size
  end

end

rails/app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: [:show, :edit, :update, :destroy]
  before_action :check_permission_for_read, only: [:show]
  before_action :check_permission_for_write, only: [:edit, :update, :destroy]

  # GET /groups
  # GET /groups.json
  def index
    @groups = Group.owned_by(current_user)
                   .order(:name)
  end

  # GET /groups/1
  # GET /groups/1.json
  def show
  end

  # GET /groups/new
  def new
    @group = Group.new
    @group.owner = current_user
    @group.rest_users_size.times do
      @group.group_users.build
    end
   end

  # GET /groups/1/edit
  def edit
    @group.rest_users_size.times do
      @group.group_users.build
    end
  end

  # POST /groups
  # POST /groups.json
  def create
    @group = Group.new(group_params)
    @group.owner = current_user
    respond_to do |format|
      if @group.save
        format.html { redirect_to @group, notice: 'Group was successfully created.' }
        format.json { render :show, status: :created, location: @group }
      else
        format.html { render :new }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /groups/1
  # PATCH/PUT /groups/1.json
  def update
    respond_to do |format|
      if @group.update(group_params)
        format.html { redirect_to @group, notice: 'Group was successfully updated.' }
        format.json { render :show, status: :ok, location: @group }
      else
        format.html { render :edit }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1
  # DELETE /groups/1.json
  def destroy
    @group.destroy
    respond_to do |format|
      format.html { redirect_to groups_url, notice: 'Group was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_group
      @group = Group.friendly.find(params[:id])
    end

    def check_permission_for_read
      unless @group.owned_by?(current_user)
        redirect_to groups_path, alert: 'You cannot read this group.' 
        return
      end
    end

    def check_permission_for_write
      unless @group.owned_by?(current_user)
        redirect_to groups_path, alert: 'You cannot write this group.' 
        return
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def group_params
      _group_params = params.require(:group).permit(:name, group_users_attributes: [:id, :user_id])
      _group_params["group_users_attributes"].each do | k, v |
        v["_destroy"] = true if v["user_id"].blank?
      end
      _group_params
    end
end

rails/app/helpers/groups_helper.rb
module GroupsHelper
end

rails/app/views/groups/_form.html.erb
<%= simple_form_for  _group do |f| %>
  <%= f.input :name %>

  <%= f.simple_fields_for :group_users do |u| %>
    <%= u.input :user_id, collection: User.without(_group.owner) %>
  <% end %>

  <%= link_to "back", groups_path, class: "btn"%>
  <%= f.submit class: ["btn", "btn-primary"] %>
<% end %>

rails/app/views/groups/edit.html.erb
<h1>Editing Group</h1>

<%= render 'form', _group: @group %>

rails/app/views/groups/index.html.erb
<h1>Groups</h1>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Users</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @groups.each do |group| %>
      <tr>
        <td><%= group.name %></td>
        <td><%= group.group_users.map{|group_user| group_user.user.name}.join(", ") %></td>

        <td>
          <%= link_to 'Show', group, class: ["btn", "btn-sm", "btn-primary"] %>
          <%= link_to 'Edit', edit_group_path(group), class: ["btn", "btn-sm", "btn-info"] %>
          <%= link_to 'Destroy', group, method: :delete, data: { confirm: 'Are you sure?' }, class: ["btn", "btn-sm", "btn-danger"]  %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Group', new_group_path, class: "btn btn-primary" %>

rails/app/views/groups/new.html.erb
<h1>New Group</h1>

<%= render 'form', _group: @group %>

rails/app/views/groups/show.html.erb
<div class="page-header">
  <h1><%= @group.name %></h1>
</div>

<ul>
  <% @group.including_users.each do |user| %>
    <li><%= user.name %> ( <%= user.email %> )</li>
  <% end %>
</ul>

<%= link_to 'Back', groups_path, class: "btn btn-default"  %>
<%= link_to 'Edit', edit_group_path(@group), class: "btn btn-info"%>