rails/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :notes do
    member do
      get   'disclosures'       => "notes#show_disclosures"
      get   'disclosures/edit'  => "notes#edit_disclosures"
      patch 'disclosures'       => "notes#update_disclosures"
    end
  end
  resources :groups

  resources :users, :except => [:index, :show]
  resources :password_auths, :only => [:new, :create, :destroy]
  
  get 'login' => 'password_auths#new', :as => :login
  post 'logout' => 'password_auths#destroy', :as => :logout

  root :to => 'notes#index'
end

rails/app/views/shared/_messages.html.erb
<% if flash[:notice].present? %>
  <div class="alert alert-info" role="alert">
    <%= flash[:notice] %>
  </div>
<% end %>
<% if flash[:alert].present? %>
  <div class="alert alert-danger" role="alert">
    <%= flash[:alert] %>
  </div>
<% end %>

rails/app/views/shared/_navbar.html.erb
    <!-- Fixed navbar -->
    <nav class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">co-Note</a>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <% if current_user %>
              <li><%= link_to "Notes", notes_path %></li>
              <li><%= link_to "Groups", groups_path %></li>
              <li><%= link_to "Profile", edit_user_path(current_user) %></li>
              <li><%= link_to "Logout", :logout, method: :post %></li>
            <% else %>
              <li><%= link_to "Register", new_user_path %></li>
              <li><%= link_to "Login", :login %></li>
            <% end %>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>